import { countIslandItems } from "@/lib/design/align";
import { useDesign } from "@/lib/design/store";
import type { BlendMode, TextNode } from "@/lib/design/types";
import { isImage, isPath } from "@/lib/design/types";
import { cn } from "@/lib/utils";
import { NumField } from "./num-field";
import { FillEditor, Section, ShadowEditor, Swatches, Field } from "./inspector-parts";
import { MixedInk } from "./mixed-ink";
import { MixedPathDash } from "./mixed-path-dash";
import { MixedFilters } from "./mixed-filters";
import { MixedType } from "./mixed-type";
import { MixedTypeColour } from "./mixed-type-colour";
import { PathFields } from "./inspector-path";
import { InspectorPrint } from "./inspector-print";
import { HotspotField, ImageFields, LinkedRow, TextFields } from "./inspector-type";
