export {
  peekAfterLostCapture,
  peekCaptionAfterMutedPointerUp,
  peekCaptionAfterMutedPointerUpCurrentHover,
  peekCaptionAfterLeaveOffCurrentNamedTick,
  peekCaptionAfterLostCaptureCurrentHover,
  peekCaptionAfterMutedPointerUpShiftRelease,
  peekCaptionAfterQuietEscape,
  peekCaptionAfterQuietEscapeShiftRelease,
  peekCaptionAfterQuietHomeEnd,
  peekCaptionAfterShiftRelease,
  peekCaptionNameId,
  peekTickAfterMutedPointerUp,
  peekTickAfterQuietHomeEnd,
  peekTickFadeShouldRestart,
  peekTickFadeShouldRestartAfterLostCapture,
} from "@/lib/design/present-idle";
