import { useEffect, useMemo, useState, type MouseEvent } from "react";
import { useNavigate } from "@tanstack/react-router";
import { Toaster } from "sonner";
import { FORMATS } from "@/lib/design/formats";
import { screenToDoc } from "@/lib/design/render";
import { useDesign } from "@/lib/design/store";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { CommandPalette, type CommandItem } from "./command-palette";
import { AiPanel } from "./ai-panel";
import { CanvasStage } from "./canvas-stage";
import { Inspector } from "./inspector";
import { LayersPanel } from "./layers-panel";
import { MixedInk } from "./mixed-ink";
import { MixedType } from "./mixed-type";
import type { DesignNode, TextNode } from "@/lib/design/types";
import { PaintDock } from "./paint-dock";
import { ToolRail } from "./tool-rail";
import { TopBar } from "./top-bar";
import { useShortcuts } from "./use-shortcuts";
import { CampaignStrip, PresentView } from "./present-chrome";
