export { holeIndexFromHoleControl, holeIndexFromPointKey } from "./path-point-key";
// Point keys: /^path-\d+$/ outer ring, /^hole-(\d+)-(\d+)$/ holes.
export {
  holePointIndexFromPointKey,
  isCrossingHoleHeaderToPointTab,
  isCrossingHolePointTab,
  isCrossingHolePointToHeaderTab,
  pickFirstOuterPointTabTarget,
  pickOffsetTabTarget,
  pickOutlineTabTarget,
  pickRoundTabTarget,
  pickSimplifyTabTarget,
  pickNextHoleHeaderTabTarget,
  pickNextHolePointTabTarget,
  pickPrevHoleHeaderTabTarget,
  pickSameHoleFirstPointTabTarget,
  pickSameHoleHeaderTabTarget,
  pickSameHoleLastPointTabTarget,
  shouldShiftTabFromFirstOuterToOffset,
  shouldShiftTabFromFirstOuterToOutline,
  shouldShiftTabFromFirstOuterToRound,
  shouldShiftTabFromFirstOuterToSimplify,
  shouldShiftTabToPrevHoleHeader,
  shouldShiftTabToSameHoleHeader,
  shouldTabFromClosedToOffset,
  shouldTabFromOffsetToFirstOuterPoint,
  shouldTabFromOffsetToOutline,
  shouldTabFromOutlineToRound,
  shouldTabFromRoundToSimplify,
  shouldTabFromSimplifyToFirstOuterPoint,
  shouldTabFromLastHoleXToNextHeader,
  shouldTabFromLastHoleYToNextHeader,
  shouldTabToNextHoleHeader,
  shouldTabToSameHoleFirstPoint,
} from "./path-point-tab-a";
export {
  labelPathInspectorControl,
  nextPathAxis,
  pathInspectorExitStatus,
  pathTabExitsAtEdge,
  pathTabLeavesList,
  pickPathInspectorExitTarget,
} from "./path-point-tab-core";
export {
  shouldTabFromLastHoleYToNextFirstY,
  shouldTabFromLastHoleYToNextFirstX,
  shouldTabFromLastHoleXToNextFirstY,
  shouldTabFromLastHoleXToNextFirstX,
  shouldShiftTabFromFirstHoleXToPrevLastY,
  shouldShiftTabFromFirstHoleXToPrevLastX,
  shouldShiftTabFromFirstHoleYToPrevLastX,
  shouldShiftTabFromFirstHoleYToPrevLastY,
  pickNextHoleFirstPointYTabTarget,
  pickNextHoleFirstPointXTabTarget,
  pickPrevHoleLastPointXTabTarget,
  pickPrevHoleLastPointYTabTarget,
  shouldTabFromLastOuterYToFirstHoleX,
  shouldTabFromLastOuterYToFirstHoleY,
  shouldTabFromLastOuterYToFirstHoleHeader,
  shouldShiftTabFromFirstHoleHeaderToLastOuterY,
  shouldShiftTabFromFirstHoleHeaderToLastOuterX,
  shouldTabFromLastOuterXToFirstHoleY,
  shouldTabFromLastOuterXToFirstHoleX,
  shouldShiftTabFromFirstHoleXToLastOuterY,
  shouldShiftTabFromFirstHoleXToLastOuterX,
  shouldShiftTabFromFirstHoleYToLastOuterX,
  shouldShiftTabFromFirstHoleYToLastOuterY,
  pickLastOuterLastPointYTabTarget,
  pickLastOuterLastPointXTabTarget,
  pickFirstHoleFirstPointXTabTarget,
  pickFirstHoleFirstPointYTabTarget,
  pickFirstHoleHeaderTabTarget,
} from "./path-point-tab-last-y";
export {
  shouldShiftTabFromNextHoleHeaderToLastHoleX,
  pickLastHoleLastPointXTabTarget,
  shouldShiftTabFromNextHoleHeaderToLastHoleY,
  pickLastHoleLastPointYTabTarget,
  shouldShiftTabFromNextHoleFirstYToLastHoleY,
  shouldShiftTabFromNextHoleFirstXToLastHoleY,
  shouldShiftTabFromNextHoleFirstXToLastHoleX,
  shouldShiftTabFromNextHoleFirstYToLastHoleX,
  shouldShiftTabFromNextHoleFirstYToLastHoleHeader,
  shouldShiftTabFromNextHoleFirstXToLastHoleHeader,
  pickLastHoleHeaderTabTarget,
  pickNextHoleFirstPointXFromHeaderTabTarget,
  shouldTabFromLastHoleHeaderToNextFirstX,
  pickNextHoleFirstPointYFromHeaderTabTarget,
  shouldTabFromLastHoleHeaderToNextFirstY,
  pickNextHoleHeaderFromHeaderTabTarget,
  shouldTabFromLastHoleHeaderToNextHeader,
  pickLastHoleHeaderFromHeaderTabTarget,
  shouldShiftTabFromNextHoleHeaderToLastHoleHeader,
  pickLastHoleFillFromHeaderTabTarget,
  shouldShiftTabFromNextHoleHeaderToLastHoleFill,
  pickNextHoleHeaderFromFillTabTarget,
  shouldTabFromHoleFillToNextHeader,
} from "./path-point-tab-next-header-x";
export {
  pickNextHoleHeaderFromDeleteTabTarget,
  shouldTabFromHoleDeleteToNextHeader,
} from "./path-point-tab-hole-delete";
export {
  lastOuterXToFirstHoleHeader,
  shouldTabFromLastOuterXToFirstHoleHeader,
} from "./path-point-tab-last-x";
export {
  pickClosedTabTarget,
  shouldShiftTabFromFirstOuterToClosed,
} from "./path-point-tab-closed";
export {
  isCrossingHoleHeaderTab,
  isPathExitStatus,
  pathRingWalkStatus,
  pickNextHoleTabTarget,
  pickPreviousHoleTabTarget,
  restoreHoleListScroll,
  restorePointListScroll,
  snapshotScroll,
  holdPointAndHoleLists,
  shouldHoldHoleListScroll,
  shouldHoldPointListScroll,
  tagHoleHeaderTabCrossing,
  tagHolePointTabCrossing,
} from "./path-point-tab-b";
