export { holeIndexFromHoleControl, holeIndexFromPointKey } from "./path-point-key";
// Point keys: /^path-\d+$/ outer ring, /^hole-(\d+)-(\d+)$/ holes.
export {
  labelPathInspectorControl,
  nextPathAxis,
  pathInspectorExitStatus,
  pathTabExitsAtEdge,
  pathTabLeavesList,
  pickPathInspectorExitTarget,
} from "./path-point-tab-core";
export {
  holePointIndexFromPointKey,
  isCrossingHoleHeaderToPointTab,
  isCrossingHolePointTab,
  isCrossingHolePointToHeaderTab,
  pickFirstOuterPointTabTarget,
  pickOffsetTabTarget,
  pickOutlineTabTarget,
  pickRoundTabTarget,
  pickSimplifyTabTarget,
  pickNextHoleHeaderTabTarget,
  pickNextHolePointTabTarget,
  pickPrevHoleHeaderTabTarget,
  pickSameHoleFirstPointTabTarget,
  pickSameHoleHeaderTabTarget,
  pickSameHoleLastPointTabTarget,
  shouldShiftTabFromFirstOuterToOffset,
  shouldShiftTabFromFirstOuterToOutline,
  shouldShiftTabFromFirstOuterToRound,
  shouldShiftTabFromFirstOuterToSimplify,
  shouldShiftTabToPrevHoleHeader,
  shouldShiftTabToSameHoleHeader,
  shouldTabFromClosedToOffset,
  shouldTabFromOffsetToFirstOuterPoint,
  shouldTabFromOffsetToOutline,
  shouldTabFromOutlineToRound,
  shouldTabFromRoundToSimplify,
  shouldTabFromSimplifyToFirstOuterPoint,
  shouldTabFromLastHoleXToNextHeader,
  shouldTabToNextHoleHeader,
  shouldTabToSameHoleFirstPoint,
} from "./path-point-tab-a";
export {
  shouldTabFromLastHoleYToNextFirstY,
  shouldTabFromLastHoleYToNextFirstX,
  shouldTabFromLastHoleXToNextFirstX,
  shouldShiftTabFromFirstHoleXToPrevLastX,
  shouldShiftTabFromFirstHoleYToPrevLastX,
  shouldShiftTabFromFirstHoleYToPrevLastY,
  pickNextHoleFirstPointYTabTarget,
  pickNextHoleFirstPointXTabTarget,
  pickPrevHoleLastPointXTabTarget,
  pickPrevHoleLastPointYTabTarget,
} from "./path-point-tab-last-y";
export {
  pickClosedTabTarget,
  shouldShiftTabFromFirstOuterToClosed,
} from "./path-point-tab-closed";
export {
  isCrossingHoleHeaderTab,
  isPathExitStatus,
  pathRingWalkStatus,
  pickNextHoleTabTarget,
  pickPreviousHoleTabTarget,
  restoreHoleListScroll,
  restorePointListScroll,
  snapshotScroll,
  holdPointAndHoleLists,
  shouldHoldHoleListScroll,
  shouldHoldPointListScroll,
  tagHoleHeaderTabCrossing,
  tagHolePointTabCrossing,
} from "./path-point-tab-b";
